#!/bin/bash

assets=$2

sudo apt install fonts-powerline -y

if [ -d "/usr/share/fonts/Menlo-for-Powerline" ]; then
  exit 0
fi

filename="Menlo-for-Powerline.tar.xz"
filepath="$assets/$filename"

sudo tar -C /usr/share/fonts -xvf "$filepath"
sudo chmod 755 /usr/share/fonts/Menlo-for-Powerline/*
fc-cache -f -v
