#!/bin/bash

sudo apt install fonts-powerline -y

assets=$2

filename="Menlo-for-Powerline.tar.xz"
filepath="$assets/$filename"

sudo tar -C /usr/share/fonts -xvf "$filepath"
sudo chmod 755 /usr/share/fonts/Menlo-for-Powerline/*
fc-cache -f -v
