#!/bin/bash

assets=$2

if [ -d "/usr/share/fonts/WindowsFonts" ]; then
  exit 0
fi

filename="WindowsFonts.tar.xz"
filepath="$assets/$filename"

sudo tar -C /usr/share/fonts -xvf "$filepath"
sudo chmod 755 /usr/share/fonts/WindowsFonts/*
fc-cache -f -v
