#!/bin/bash

sudo apt update
sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
sudo apt install docker.io docker-compose -y
sudo usermod -aG docker $USER
